//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filmotekica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class glumac
    {
        public int id { get; set; }
        public string imeglumca { get; set; }
        public string prezimeglumca { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    }
}
