//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filmotekica.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FilmotekicaDBEntities : DbContext
    {
        public FilmotekicaDBEntities()
            : base("name=FilmotekicaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<film> films { get; set; }
        public virtual DbSet<glumac> glumacs { get; set; }
        public virtual DbSet<reziser> rezisers { get; set; }
        public virtual DbSet<zanr> zanrs { get; set; }
    }
}
